name: Meilisearch Indexer

on:
  push

  # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout documentation repository
        uses: actions/checkout@v3

      - name: show contents
        run: |
          ls -la

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: create env
        run: |
          touch .env
          echo PATH_TO_DOCUMENTS=./docs/ >> .env
          echo MEILI_INDEX=grid-documentation >> .env
          echo MEILI_ADMIN_HOST=${{secrets.MEILI_ADMIN_HOST}} >> .env
          echo MEILI_ADMIN_KEY=${{secrets.MEILI_ADMIN_KEY}} >> .env

      - name: run metacheck
        run: |
          npm install
          npm run meta-check
           npm run build

      - name: run indexer
        run: |

          npm run index
